twilio/twilio-client.js

- README.md
- package.json
> Add badges and fix lodash dependency

- lib/twilio/rtc/monitor.ts
- tests/unit/rtc/monitor.ts
Adjusting threshold to use min for iceRestarts instead of maxDuration.
Adding option to pass raiseCount, sampleCount, and clearCount as parameters
> adjusting thresholds for icerestarts

- lib/twilio/connection.ts
- lib/twilio/util.js
- tests/unit/connection.ts
- [CLIENT-6049](https://issues.corp.twilio.com/browse/CLIENT-6049)
This PR reports average audio levels to insights instead of the last emitted audio level.
> CLIENT-6049 | Emitting average audio levels

- package.json
Fixing security vulnerability for js-yaml module.
https://github.com/twilio/twilio-client.js/network/alerts
> Updating yaml to fix security vulnerability

- lib/twilio/connection.ts
- lib/twilio/device.ts
- lib/twilio/rtc/monitor.ts
- tslint.json
Adding member-ordering on our tslint
> Tslint member order

- package.json
Fixing lodash security issue.
https://github.com/twilio/twilio-client.js/network/alert/package.json/lodash/open
https://github.com/lodash/lodash/pull/4336
> Fixing lodash security issue

- lib/twilio/connection.ts
- lib/twilio/device.ts
- lib/twilio/rtc/peerconnection.js
- tests/peerconnection.js
- tests/unit/connection.ts
- tests/unit/device.ts
- [CLIENT-6400](https://issues.corp.twilio.com/browse/CLIENT-6400)
Adding flag to enable/disable auto ice restart
> CLIENT-6400 | Implement enableIceRestart flag

- CHANGELOG.md
- [CLIENT-0000](https://issues.corp.twilio.com/browse/CLIENT-0000)
> Update changelog for upcoming media reconnect flag

- lib/twilio/connection.ts
- lib/twilio/rtc/monitor.ts
- lib/twilio/rtc/peerconnection.js
- tests/peerconnection.js
- tests/unit/connection.ts
- [CLIENT-6444](https://issues.corp.twilio.com/browse/CLIENT-6444)
Implemented media connection management base on https://docs.google.com/document/d/1Ul1Z0yFOAUv8iopB6PQ0PsrWp8jrEz-T67YbBr9jt60/edit#heading=h.sh61l278o4f7
JS-related summary is here https://issues.corp.twilio.com/browse/CLIENT-6444
> CLIENT-6444 | Connection Management

- CHANGELOG.md
> Updates changelog for 1.8

- CHANGELOG.md
Update the text with the same info as the mobile SDK release for max average bitrate
- [CLIENT-0000](https://issues.corp.twilio.com/browse/CLIENT-0000)
> Updated change log text and example

- lib/twilio/errors/generated.ts
- scripts/errors.js
> Hiding error vars from tsdoc

- CHANGELOG.md
> Changelog for CLIENT-6779

- .release.json
- package.json
[CLIENT-6859](https://issues.corp.twilio.com/browse/CLIENT-6859) | Fixing CI script
> CLIENT-6859 | Fixing CI script

- lib/twilio/connection.ts
- lib/twilio/rtc/peerconnection.js
- tests/peerconnection.js
- tests/unit/connection.ts
[CLIENT-6885](https://issues.corp.twilio.com/browse/CLIENT-6885) ICE Gathering failures and timeouts issue ICE Restarts.
> Client 6885 | ICE Gathering failures and timeouts issue ICE Restarts

- CHANGELOG.md
Change log for Client 6885 | ICE Gathering failures and timeouts
> Change log for Client 6885 | ICE Gathering failures and timeouts

- CHANGELOG.md
[CLIENT-6957](https://issues.corp.twilio.com/browse/CLIENT-6957) - Update CHANGELOG.md for 1.9.6 release
> CLIENT-6957 | Update CHANGELOG.md for 1.9.6 release

- lib/twilio/connection.ts
- lib/twilio/device.ts
- lib/twilio/rtc/peerconnection.js
- lib/twilio/rtc/rtcpc.js
- lib/twilio/rtc/sdp.js
- lib/twilio/util.js
- tests/integration/icenomination.ts
- tests/integration/reconnection.ts
- tests/lib/util.js
- tests/peerconnection.js
- tests/sdp.js
- tests/unit/device.ts
- tests/util.js
[CLIENT-7025](https://issues.corp.twilio.com/browse/CLIENT-7025)
> CLIENT-7025 | Parameterize ICE Aggressive Nomination

- CHANGELOG.md
CLIENT-7025-Changelog for 1.9.7 release
> CLIENT-7025-Changelog

- lib/twilio/constants.js
- templates/constants.js
- [CLIENT-7221](https://issues.corp.twilio.com/browse/CLIENT-7221)
Updating sound base url to use sdk.twilio.com
> CLIENT-7221 | Updating sound base url to use sdk.twilio.com

- lib/twilio.ts
- lib/twilio/errors/index.ts
- [CLIENT-0000](https://issues.corp.twilio.com/browse/CLIENT-0000)
> Fixing typedoc

- CHANGELOG.md
- lib/twilio/device.ts
- lib/twilio/eventpublisher.js
- tests/eventpublisher.js
- tests/unit/device.ts
https://code.hq.twilio.com/client/rtc-insights-spec/pull/50
> CLIENT-7541 | Add appName and appVersion

- CHANGELOG.md
- lib/twilio.ts
- lib/twilio/device.ts
- lib/twilio/pstream.js
- tests/pstream.js
- tests/unit/connection.ts
- tests/unit/device.ts
Cherry picking 2 patches from master for 1.10.2 release
> Cherry picking 2 patches from master for 1.10.2 release

- tests/integration/icenomination.ts
> Update docker tests

- CHANGELOG.md
- lib/twilio/device.ts
- lib/twilio/eventpublisher.js
- tests/eventpublisher.js
Revert "CLIENT-7541 | Add appName and appVersion (#145)"
This will be submitted to a feature branch instead.
> Revert "CLIENT-7541 | Add appName and appVersion (#145)"

- CHANGELOG.md
- lib/twilio/device.ts
- lib/twilio/regions.ts
- lib/twilio/wstransport.ts
- package.json
- tests/unit/device.ts
- tests/unit/regions.ts
Reopening https://github.com/twilio/twilio-client.js/pull/141 so it's submitted to 1.11 branch instead. This has been approved already and should be ok to merge.
> Reopen PR "[CLIENT-7519] Support for edge in Device.Options"

- CHANGELOG.md
- lib/twilio/constants.js
- lib/twilio/device.ts
- lib/twilio/pstream.js
- lib/twilio/regions.ts
- lib/twilio/wstransport.ts
- tests/docker/proxy/server.js
- tests/integration/edgefallback.ts
- tests/lib/util.js
- tests/mock/WSTransport.js
- tests/pstream.js
- tests/unit/device.ts
- tests/unit/regions.ts
- tests/unit/wstransport.ts
- [CLIENT-7562](https://issues.corp.twilio.com/browse/CLIENT-7562)
Implemented regional edge fallback. See [CLIENT-7562](https://issues.corp.twilio.com/browse/CLIENT-7562) ticket for specs.
> CLIENT-7562 | Adding edge fallback support

- PREFLIGHT.md
- lib/twilio/preflight/preflight.ts
- tests/unit/preflight.ts
- [CLIENT-7501](https://issues.corp.twilio.com/browse/CLIENT-7501)
> CLIENT-7501 | Fail the test on websocket timeout

- CHANGELOG.md
- lib/twilio/device.ts
- lib/twilio/rtc/rtcpc.js
- lib/twilio/util.js
- tests/util.js
This has been reviewed and approved in this PR https://github.com/twilio/twilio-client.js/pull/155
This PR is for merging this feature to 1.11.
> CLIENT-7575 | Log warning for deprecated browsers

- lib/twilio/regions.ts
- tests/unit/regions.ts
- [CLIENT-7658](https://issues.corp.twilio.com/browse/CLIENT-7658)
> CLIENT-7658 | Allow roaming as an edge fallback

- README.md
https://github.com/twilio/twilio-client.js/issues/172
> GH 172 | Adding import to readme

- CHANGELOG.md
- PREFLIGHT.md
- PREFLIGHT_TWIML.md
- lib/twilio/constants.js
- lib/twilio/device.ts
- lib/twilio/errors/index.ts
- lib/twilio/preflight/preflight.ts
- templates/constants.js
- tests/integration/preflight.ts
- tests/unit/preflight.ts
- [CLIENT-7627](https://issues.corp.twilio.com/browse/CLIENT-7627)
See ticket details
> CLIENT-7627 | Remove mic dependency on preflight

- CHANGELOG.md
- lib/twilio/connection.ts
- package.json
Replace CHANGELOG description and docs with the descriptions used in our IDL.
> Update callerInfo docs and CHANGELOG

- PREFLIGHT.md
- lib/twilio/preflight/preflight.ts
- lib/twilio/rtc/stats.js
- tests/unit/preflight.ts
Handle scenario where no candidates are selected during ICE negotiation on preflight.
> Handle scenario where no candidates are selected on preflight.

- CHANGELOG.md
- lib/twilio/connection.ts
- tests/integration/stirshaken.ts
- tests/unit/connection.ts
[CLIENT-7779](https://issues.corp.twilio.com/browse/CLIENT-7779)
- Remove isPstn regex. If StirStatus is undefined, we set callerInfo to null.
- Verify adding extra VSP params will not crash the SDK
> CLIENT-7779 | Remove isPstn regex and update test for STIR/SHAKEN

- CHANGELOG.md
> Update changelog for 1.12.0

- CHANGELOG.md
- lib/twilio/connection.ts
- tests/unit/connection.ts
- [CLIENT-7789](https://issues.corp.twilio.com/browse/CLIENT-7789)
> CLIENT-7789 | Dont emit disconnect on cancel

- README.md
- [CLIENT-7825](https://issues.corp.twilio.com/browse/CLIENT-7825)
> CLIENT-7825 | Documenting content security policy

- CHANGELOG.md
- lib/twilio/device.ts
- lib/twilio/regions.ts
- [CLIENT-7871](https://issues.corp.twilio.com/browse/CLIENT-7871)
> CLIENT-7871 | Replace edge name  sao-paolo with sao-paulo

- CHANGELOG.md
- PREFLIGHT.md
- lib/twilio/preflight/preflight.ts
- lib/twilio/rtc/stats.js
- tests/spec/rtcicecandidates-with-transport.json
- tests/spec/rtcicecandidates-without-transport.json
- tests/stats.js
- tests/unit/preflight.ts
- [CLIENT-7923](https://issues.corp.twilio.com/browse/CLIENT-7923)
> CLIENT-7923 | Rename ICE Candidates to ICE Candidate Stats

- CHANGELOG.md
- PREFLIGHT.md
- lib/twilio/preflight/preflight.ts
- lib/twilio/preflight/timing.ts
- tests/unit/preflight.ts
- [CLIENT-7726](https://issues.corp.twilio.com/browse/CLIENT-7726)
> CLIENT-7726 | Add signaling timing in the Preflight report

- CHANGELOG.md
- README.md
- lib/twilio/device.ts
- lib/twilio/eventpublisher.js
- lib/twilio/regions.ts
- tests/eventpublisher.js
- tests/unit/device.ts
- tests/unit/regions.ts
- [CLIENT-7932](https://issues.corp.twilio.com/browse/CLIENT-7932)
EDIT: ~~Code complete but needs tests and a changelog entry. An initial review would help.~~
Code complete and added unit tests. Complete changelog entry will be populated before  shipping. End-to-end tests are not ready to get implemented yet. They will get added once backend deploys to prod. I tested manually on dev server for now.
This PR implements regional authentication for insights.
FRD: https://code.hq.twilio.com/client/sdk-frd/blob/master/voice/voice-regional-insights.md
Generating regional auth: …
> CLIENT-7932 | Regional authentication for insights

- README.md
> Update Readme with latest release of twilio-client

- CHANGELOG.md
- lib/twilio/connection.ts
- lib/twilio/statsMonitor.ts
- package.json
- tests/unit/connection.ts
- tests/unit/statsMonitor.ts
- [CLIENT-7589](https://issues.corp.twilio.com/browse/CLIENT-7589)
Update the warning threshold for `packetsLostFraction` to match the referenced IDL in the JIRA link.
> [CLIENT-7589] Update warning threshold for `packetsLostFraction`.

- CHANGELOG.md
- lib/twilio/connection.ts
- lib/twilio/statsMonitor.ts
- tests/unit/connection.ts
- tests/unit/statsMonitor.ts
- [CLIENT-7613](https://issues.corp.twilio.com/browse/CLIENT-7613)
This PR updates the `constant-audio-level` warning threshold to match the IDL as per CLIENT-7538.
> [CLIENT-7613] Update `constant-audio-level` warning.

- lib/twilio/statsMonitor.ts
- tests/unit/statsMonitor.ts
- [CLIENT-7589](https://issues.corp.twilio.com/browse/CLIENT-7589)
Check sample before emitting
> CLIENT-7589 | Check sample count before emitting

- lib/twilio/regions.ts
> Add au1-ix and jp1-ix to known regions

- lib/twilio.ts
> CLIENT-8266 | Remove singleton behavior

- lib/twilio/connection.ts
- tests/unit/connection.ts
> CLIENT-8298 | Remove deprecated methods from Connection

- CHANGELOG.md
- lib/twilio/connection.ts
- lib/twilio/device.ts
- lib/twilio/rtc/peerconnection.js
- tests/integration/reconnection.ts
- tests/peerconnection.js
- tests/unit/connection.ts
- tests/unit/device.ts
- [CLIENT-8268](https://issues.corp.twilio.com/browse/CLIENT-8268)
This PR removes deprecated `Device` options for sane defaults as part of `twilio-client.js@2.x`.
> [CLIENT-8268] Remove options for sane defaults.

- lib/twilio/device.ts
- lib/twilio/errors/generated.ts
- lib/twilio/errors/index.ts
- lib/twilio/errors/twilioError.ts
- scripts/errors.js
- tests/integration/device.ts
- tests/integration/edgefallback.ts
- tests/integration/icenomination.ts
- tests/integration/opus.ts
- tests/integration/preflight.ts
- tests/integration/reconnection.ts
- tests/integration/stirshaken.ts
- tests/unit/device.ts
- [CLIENT-8267](https://issues.corp.twilio.com/browse/CLIENT-8267)
Clean up old method interfaces and public members / options on Device.
> [CLIENT-8267] Clean up old method interfaces and public members / options on Device

- CHANGELOG.md
- lib/twilio/connection.ts
- lib/twilio/device.ts
- tests/integration/device.ts
- tests/integration/icenomination.ts
- tests/integration/opus.ts
- tests/integration/preflight.ts
- tests/integration/reconnection.ts
- tests/integration/stirshaken.ts
- tests/unit/connection.ts
- tests/unit/device.ts
https://issues.corp.twilio.com/browse/CLIENT-8299
> CLIENT-8299 | Move constraints and config into options objects

- CHANGELOG.md
- lib/twilio/connection.ts
- lib/twilio/device.ts
- lib/twilio/preflight/preflight.ts
- tests/integration/device.ts
- tests/integration/icenomination.ts
- tests/unit/connection.ts
- tests/unit/device.ts
- tests/unit/preflight.ts
See CHANGELOG for details.
TODO: Figure out what to do about missing Errors for getUserMedia failures. Will probably need to add new twilio-voice-errors entries.
> Client 8300

- CHANGELOG.md
- lib/twilio/device.ts
- lib/twilio/preflight/preflight.ts
- tests/integration/device.ts
- tests/integration/edgefallback.ts
- tests/integration/icenomination.ts
- tests/integration/mutableOptions.ts
- tests/integration/opus.ts
- tests/integration/preflight.ts
- tests/integration/reconnection.ts
- tests/integration/stirshaken.ts
- tests/unit/device.ts
- tests/unit/preflight.ts
- [CLIENT-8270](https://issues.corp.twilio.com/browse/CLIENT-8270)
> [CLIENT-8270] Mutable `Device` options.

- README.md
- package.json
Renaming package to `@twilio/voice-client` and renaming the SDK to be more precise, `Twilio Voice Client SDK`.
> Client 8321

- CHANGELOG.md
- lib/twilio/device.ts
- tests/integration/mutableOptions.ts
- tests/unit/device.ts
Makes CHANGELOG.md more organized, and up-to-date
Fixed some API quirks
> Pretty up changelog, small API tweaks

- lib/twilio/device.ts
- tests/unit/device.ts
- [CLIENT-8393](https://issues.corp.twilio.com/browse/CLIENT-8393)
This PR fixes errors emitted by the `Device`.
> [CLIENT-8393] Fix error code priority.

- README.md
Add a link to the 2.0 pilot to the README
> Add a link to the 2.0 pilot

- lib/twilio/device.ts
[related issue](https://github.com/twilio/twilio-client.js/issues/225)
> fix: listeners not cleaned up after device destroy

- CHANGELOG.md
- [VBLOCKS-291](https://issues.corp.twilio.com/browse/VBLOCKS-291)
> [VBLOCKS-291] Fix changelog typos.

- tests/electron/main.js
- N/A
This PR redacts leaked credentials.
> Redact leaked credentials

- CHANGELOG.md
- README.md
- lib/twilio/device.ts
- lib/twilio/eventpublisher.js
- lib/twilio/regions.ts
- tests/eventpublisher.js
- tests/unit/device.ts
- tests/unit/regions.ts
If you look at the commit history since the last release (1.14), there are changes that weren't release. This PR is undoing those changes.
> Removing unreleased changes

- CHANGELOG.md
- lib/twilio/audiohelper.ts
- lib/twilio/connection.ts
- lib/twilio/device.ts
> Adding docs and changelog

- CHANGELOG.md
This is the same changelog PR in 2.x, which was already approved
https://github.com/twilio/twilio-voice.js/pull/211. Merging..
> Update 2.7.2 CHANGELOG.md to reflect Sonoma issue.

- CHANGELOG.md
- [VBLOCKS-838](https://issues.corp.twilio.com/browse/VBLOCKS-838)
This PR fixes a broken link to a support article in our changelog.
> [VBLOCKS-838] Fix broken link to support articles
