CHANGELOG.md
lib/twilio/rtc/peerconnection.js
tests/peerconnection.js

- [CLIENT-6116](https://issues.corp.twilio.com/browse/CLIENT-6116)
Changing input device and calling mute right after connection, will not mute the device. This happens because we don't wait for replaceTracks to return. This PR will address that.

CLIENT-6116 | Fix mute does not work right after changing input device

---

CHANGELOG.md
lib/twilio/connection.ts
lib/twilio/eventpublisher.js
lib/twilio/rtc/monitor.js
lib/twilio/rtc/peerconnection.js
lib/twilio/rtc/rtcpc.js
tests/peerconnection.js
tests/unit/connection.ts

- [CLIENT-6145](https://issues.corp.twilio.com/browse/CLIENT-6145)
- [CLIENT-5873](https://issues.corp.twilio.com/browse/CLIENT-5873)
ICE Connections will now attempt to reconnect when they transition to the `failed` state, rather than immediately disconnecting. See [Jira CLIENT-6145](https://issues.corp.twilio.com/browse/CLIENT-6145) for more details.

CLIENT-6145 CLIENT-5873 | Restart ICE when PeerConnection is disconnected

---

CHANGELOG.md
lib/twilio/connection.ts
tests/unit/connection.ts

Changing warning delay from 20 seconds to 5 seconds

Adjust warning delay from 20 secs to 5 secs

---

CHANGELOG.md
lib/twilio/pstream.js
tests/pstream.js

- [CLIENT-6229](https://issues.corp.twilio.com/browse/CLIENT-6229)
Fixes a bug causing some signaling errors to not trigger an error event from Connection.

CLIENT-6229 | Fix bug causing some websocket errors to not surface

---

lib/twilio/connection.ts
tests/unit/connection.ts

- [CLIENT-6252](https://issues.corp.twilio.com/browse/CLIENT-6252)
Stop iceRestart loop on disconnect to prevent infinite restart on hangup if the warning is not cleared.

CLIENT-6252 | Stop iceRestart on disconnect

---

CHANGELOG.md
lib/twilio/connection.ts
lib/twilio/deferred.ts
lib/twilio/device.ts
lib/twilio/pstream.js
lib/twilio/rtc/peerconnection.js
tests/index.ts
tests/peerconnection.js
tests/pstream.js
tests/unit/connection.ts
tests/unit/deferred.ts
tests/unit/device.ts

- [CLIENT-6319](https://issues.corp.twilio.com/browse/CLIENT-6319)
@ryan-rowland  I found a 100% repro steps. See jira link above.
Update summary:
- iceRestart now returns a boolean flag `canRetry` so that the calling function can decide whether it should stop retrying. To make this possible, I made reinvite its own function. It wraps the websocket calls and responses into a promise to easily determine whether the reinvite for a callsid succeeded or failed. Success means we received an `answer`, failed means we received a `hangup` from the server. This helps on stopping the iceRestart loop. …

Client 6319 | Stop sending reinvites on server hangup

---

CHANGELOG.md
lib/twilio/connection.ts
lib/twilio/rtc/monitor.ts
lib/twilio/rtc/warning.ts

- [CLIENT-6341](https://issues.corp.twilio.com/browse/CLIENT-6341)
- [CLIENT-6342](https://issues.corp.twilio.com/browse/CLIENT-6342)
- do not trigger ice restart if total bytes is zero
- when websocket gets disconnected, we also disconnect the current call since there's no way to resume the call once websocket is disconnected.
**Details why it's happening only on Firefox:**
Firefox throws an error when calling createOffer during iceRestart when you lose internet connection. We rely on the server to return a 'hangup' event to stop retrying. Since firefox won't get passed the createOffer …

CLIENT-6341 CLIENT-6342 | Ignore warnings if total bytes is zero. Disconnect on signaling failed

---

CHANGELOG.md
lib/twilio/connection.ts
lib/twilio/pstream.js
lib/twilio/rtc/peerconnection.js
tests/peerconnection.js
tests/unit/connection.ts

- [CLIENT-6383](https://issues.corp.twilio.com/browse/CLIENT-6383)
- [CLIENT-6372](https://issues.corp.twilio.com/browse/CLIENT-6372)
- We were using `pstream.on('offline')` to detect network drops which would disconnect the active connection. But signaling server also emits 'offline' event when the token expires, which causes unwanted disconnection. This PR switches to `transport.on('close')` instead which gets emitted on websocket close.
- We are now ignoring iceRestart if signaling state is not `have-local-offer`, which usually happens when a createOffer came in late and a previous …

Client 6383 client 6372 | Listening to websocket close and checking for signaling state before applying answer

---

lib/twilio/connection.ts
lib/twilio/device.ts
lib/twilio/rtc/peerconnection.js
package.json
tests/integration/device.ts
tests/integration/opus.ts
tests/peerconnection.js
tests/unit/connection.ts
tests/unit/device.ts

- [CLIENT-6284](https://issues.corp.twilio.com/browse/CLIENT-6284)
* Implements the following
* Reconnection FRD: https://code.hq.twilio.com/client/sdk-frd/blob/master/voice/reconnection.md
* Insight events: https://wiki.hq.twilio.com/pages/viewpage.action?spaceKey=ENDA&title=Programmable+Voice+-+Event+List
* Deprecates the following
* `Connection.status()` to `Connection.state()`
* `Connection.on('disconnect')` to `Connection.on('disconnected')`
* `Connection.Status.Open` to `Connection.Status.Connected`
* `Connection.Status.Closed` to `Connection.Status.Disconnected`
* …

CLIENT-6284 | Reconnection state APIs

---

lib/twilio/connection.ts
tests/unit/connection.ts

This PR removes listening for `pstream.transportClosed` from inside connection if ice restart is disabled. Initially, transportClosed was used because firefox doesn't trigger disconnect when websocket is closed. But with iceRestart disabled, we should rely on media signaling to raise the disconnect event so we don't lose 31003 error code.

Ignore transportClosed if iceRestart is disabled

---

CHANGELOG.md
lib/twilio/connection.ts
lib/twilio/device.ts
package.json
tests/unit/connection.ts

- [CLIENT-6284](https://issues.corp.twilio.com/browse/CLIENT-6284)
- Add new `reconnecting` event on transition to new `reconnecting` state
- Add new `reconnected` event on transition from `reconnecting` to `open`
- Publishing events to insights on reconnection and on reconnected
- Adding ice_restart_enabled on insights default payload

CLIENT-6284 | Adding reconnecting and reconnected events 

---

lib/twilio.js
lib/twilio/device.ts
package.json
scripts/version.js
templates/constants.js

This removes the package.json from our dependencies and moves it into a build step. Also adds `Device.version` for reflection.

CLIENT-6392 | Remove package.json dependency

---

CHANGELOG.md
lib/twilio/connection.ts
lib/twilio/device.ts
lib/twilio/rtc/peerconnection.js

- [CLIENT-6539](https://issues.corp.twilio.com/browse/CLIENT-6539)
- Get audio levels without relying on requestAnimationFrame which won't trigger when a tab is inactive or when running as an extension.
- Adding insights whether running as an extension.

CLIENT-6539 | Getting audio levels and add insights for extensions

---

CHANGELOG.md
lib/twilio/rtc/peerconnection.js
tests/peerconnection.js

- [CLIENT-6581](https://issues.corp.twilio.com/browse/CLIENT-6581)
We are now creating a new instance of RTCPC for every PeerConnection.

CLIENT-6581 | Dont use RTCPC singleton

---

lib/twilio/connection.ts
lib/twilio/rtc/sdp.js
tests/sdp.js
tests/unit/connection.ts

This adds the following event based off of the [mobile implementation](https://github.com/twilio/rtc-cpp/pull/1105):
```js
group: settings
name: codec
payload:
codec_params: string // eg: 'maxaveragebitrate=12000;usedtx=1'
selected_codec: string // eg: 'opus/48000/2'
```
If either or neither of the codec name or codec params are found, an empty string will be reported in its place.
This uses the SDP we get after applying the remote answer, for both incoming and outgoing calls.

Add the settings:codec event after remote answer is applied

---

CHANGELOG.md
lib/twilio/sound.js
package.json
tests/sound.js

- [CLIENT-6632](https://issues.corp.twilio.com/browse/CLIENT-6632)
Currently, ringtone media files are always downloaded whenever we play them. Audio elements are always being created as well. This PR caches the Audio elements to prevent re-downloading of media files. Cache is invalidated if we change sinkIds.

CLIENT-6632 | Don't always download ringtones

---

lib/twilio/connection.ts
tests/unit/connection.ts

Add another case for publishing the `denied` insight event based on the `NotAllowedError` that `getUserMedia` might return. 
- [CLIENT-6663](https://issues.corp.twilio.com/browse/CLIENT-6663)

[CLIENT-6663] Fix error handling for getUserMedia

---

.dockerignore
Dockerfile
docker-compose.yml

Recently, we had an issue where artifacts cannot be deleted which breaks release process. This happens because docker is taking over the files that are mounted. This PR will not mount the files, but copy instead.

Copying workingdir instead of mounting to fix permission issues

---

CHANGELOG.md
lib/twilio/sound.js
tests/sound.js

- [CLIENT-6786](https://issues.corp.twilio.com/browse/CLIENT-6786)
Make sure the browser always retrieves the resource using CORS.
By default when using media tags, origin header is not sent to server
which causes the server to not return CORS headers. When this caches
on the CDN or browser, it causes issues to future requests that needs CORS,
which is true when using AudioContext. Please note that we won't have to do this
once we migrated to CloudFront.

CLIENT-6786 | Retrieve CORS headers when using media element

---

CHANGELOG.md
lib/twilio/device.ts

- [CLIENT-6832](https://issues.corp.twilio.com/browse/CLIENT-6832)
After adding crossorigin attribute in CLIENT-6786, we need to make sure we bust the browser cache to make sure CORS headers are downloaded if the customer decides to use AudioContext.
This PR is updating cache buster.

CLIENT-6832 | Update querystring to clear cache for audio

---

CHANGELOG.md
lib/twilio/connection.ts
lib/twilio/device.ts
lib/twilio/regions.ts
lib/twilio/wstransport.ts
tests/index.ts
tests/unit/device.ts
tests/unit/regions.ts
tests/unit/wstransport.ts

- [CLIENT-6831](https://issues.corp.twilio.com/browse/CLIENT-6831)
This PR removes region checking logic to allow for the use of free-strings as region shortcodes. At the moment, there is no difference in the signaling stack logic between a network loss error and an incorrect region error, meaning that if the websocket can not connect in either case, we have the same error (and consequentially the same reconnect logic).

[CLIENT-6831] Remove region checking logic

---

CHANGELOG.md
lib/twilio/connection.ts
lib/twilio/rtc/peerconnection.js
tests/peerconnection.js
tests/unit/connection.ts

- [CLIENT-6869](https://issues.corp.twilio.com/browse/CLIENT-6869)
Adding insight events when PeerConnection.connectionState changes.

CLIENT-6869 | Adding PeerConnection.connectionState insights

---

lib/twilio/connection.ts
tests/unit/connection.ts

- [CLIENT-6897](https://issues.corp.twilio.com/browse/CLIENT-6897)
Dont hangup on getUserMedia failure

CLIENT-6897 | Dont hangup on getUserMedia failure

---

CHANGELOG.md
lib/twilio/connection.ts
lib/twilio/rtc/candidate.ts
lib/twilio/rtc/peerconnection.js
tests/index.ts
tests/unit/candidate.ts
tests/unit/connection.ts

- [CLIENT-6957](https://issues.corp.twilio.com/browse/CLIENT-6957)
Sending ICE candidates to insights.
`url` is not supported by the browsers. We cannot get stun/turn url for each candidate.
Only chrome supports these properties, as shown in the PR. Other browsers will only publish properties that are supported. See https://developer.mozilla.org/en-US/docs/Web/API/RTCIceCandidate

CLIENT-6957 | Sending Local ICE candidates to insights

---

.circleci/config.yml

Adding a CircleCI config to automatically trigger QE tests when RC is cut. @charliesantos could you please +1 the PR so that I can get started with setting up a circle ci job for triggering QE tests when RC is cut?

Add circle ci config to trigger QE e2e tests when RC is cut

---

lib/twilio/connection.ts
lib/twilio/rtc/peerconnection.js
tests/peerconnection.js
tests/unit/connection.ts

- [CLIENT-6913](https://issues.corp.twilio.com/browse/CLIENT-6913)
Publishes dtls transport states to insights with the following values:
https://developer.mozilla.org/en-US/docs/Web/API/RTCDtlsTransport/state
RTC insights specs: https://code.hq.twilio.com/client/rtc-insights-spec#dtls-transport-state-events

CLIENT-6913 | Sending DTLS state changes to insights

---

PREFLIGHT_TWIML.md
lib/twilio/device.ts
lib/twilio/preflight/preflight.ts
tests/integration/preflight.ts
tests/unit/preflight.ts

- [CLIENT-7385](https://issues.corp.twilio.com/browse/CLIENT-7385)
This PR removes the `connectParams` and `callSeconds` requirement. We now provide a twiml app that allows audio recording and playback. Also provided twiml template and instructions for customers who wants to replicate the twiml.

CLIENT-7385 | Using twiml app that can record and play audio

---

lib/twilio/connection.ts
lib/twilio/pstream.js
lib/twilio/rtc/peerconnection.js
tests/index.ts
tests/mock/WSTransport.js
tests/peerconnection.js
tests/pstream.js
tests/unit/connection.ts

- [CLIENT-4533](https://issues.corp.twilio.com/browse/CLIENT-4533)
This PR adds distinct PStream methods for each type of PStream/VSP message, so that all payload unit tests can reside in PStream. It also replaces all calls to `PStream.publish()` with the appropriate PStream methods.

CLIENT-4533 Unit tests for PStream/VSP payloads.

---

PREFLIGHT.md
lib/twilio/device.ts
lib/twilio/preflight/preflight.ts
tests/integration/preflight.ts
tests/unit/device.ts
tests/unit/preflight.ts

- [CLIENT-7458](https://issues.corp.twilio.com/browse/CLIENT-7458)
This PR removes the insights related error event per team's discussion. This also removes the error handler in the preflight test because Insights connection error is the only error event that preflight was catching.

CLIENT-7458 | Removing previously added insights error

---

CHANGELOG.md
lib/twilio/asyncQueue.ts
lib/twilio/sound.js
tests/index.ts
tests/sound.js
tests/unit/asyncQueue.ts

- [CLIENT-7482](https://issues.corp.twilio.com/browse/CLIENT-7482)
Using async queue for async operations for sounds to fix the issue where error is thrown if play() and stop() are called subsequently.

CLIENT-7482 | Using async queue for async operations for sounds

---

CHANGELOG.md
lib/twilio.ts
lib/twilio/device.ts
lib/twilio/pstream.js
tests/pstream.js
tests/unit/connection.ts
tests/unit/device.ts

- [CLIENT-7544](https://issues.corp.twilio.com/browse/CLIENT-7544)
The way we export PStream in js breaks the generated ts declarations. This PR updates how we export it.

CLIENT-7544 | Fix angular build when used as npm module

---

CHANGELOG.md
lib/twilio/device.ts
lib/twilio/rtc/rtcpc.js
lib/twilio/util.js
tests/util.js

- [CLIENT-7575](https://issues.corp.twilio.com/browse/CLIENT-7575)
As part of Microsoft Legacy Edge EOL, we need to log a warning before fully removing support in Sept 2020. This PR logs a warning about deprecating Legacy Edge after calling `device.setup()` 
See EOL plan for more details.
https://docs.google.com/document/d/1CeLIr7Wr4wQBUbS3KllUn7iOHXKCXYXL5GxkOoNHDVM/edit#heading=h.um8h927b0i56
Source for detecting Legacy Edge vs Chromium Edge:
https://docs.microsoft.com/en-us/microsoft-edge/web-platform/user-agent-string

CLIENT-7575 | Log warning for deprecated browsers

---

PREFLIGHT.md
lib/twilio/preflight/preflight.ts
tests/integration/preflight.ts
tests/unit/preflight.ts

- [CLIENT-7483](https://issues.corp.twilio.com/browse/CLIENT-7483)
This PR adds two parameters to the report that `Preflight Test` emits upon test completion:
- `selectedRegion` the region that was preferred in `PreflightTest.Options`
- `region` the region that the signaling layer ended up connecting to

[CLIENT-7483] Implement region in Preflight Test.

---

lib/twilio/wstransport.ts
tests/integration/edgefallback.ts
tests/unit/wstransport.ts

- [CLIENT-7652](https://issues.corp.twilio.com/browse/CLIENT-7652)
Still needs tests but an initial review on the solution would help. I'm not 100% happy with the approach but this seems to be the simplest solution I found considering different browser behaviors. I intentionally made it verbose for readability.
EDIT: This is now ready. I removed isSafari check and added a fallback counter instead to cover all browsers.

CLIENT-7652 | Don't fallback edge when coming from connected

---

PREFLIGHT_TWIML.md
lib/twilio/preflight/preflight.ts
lib/twilio/rtc/sample.ts
tests/unit/preflight.ts

- [CLIENT-7502](https://issues.corp.twilio.com/browse/CLIENT-7502)
This PR introduces a change to Preflight Test such that samples emitted by the connection are also emitted by the test even when MOS is `null`.

[CLIENT-7502] Emit samples even when MOS is `null`.

---

tests/integration/reconnection.ts

Tests in docker that requires turning on/off network multiple times now causes errors in latest firefox, where karma loses handle. Adding a longer timer doesn't seem to fix it. Disabling the test for now and we can probably fix this by implementing a way to run test suites in separate docker containers. Filed ticket https://issues.corp.twilio.com/browse/CLIENT-7771

Disabling flaky firefox test for now

---

tests/integration/reconnection.ts

Tests in docker that requires turning on/off network multiple times now causes errors in latest firefox, where karma loses handle. Adding a longer timer doesn't seem to fix it. Disabling the test for now and we can probably fix this by implementing a way to run test suites in separate docker containers. Filed ticket https://issues.corp.twilio.com/browse/CLIENT-7771

Disabling firefox flaky test temporarily

---

CHANGELOG.md
config.example.yaml
docker-compose.yml
karma.conf.ts
lib/twilio/connection.ts
tests/env.js
tests/integration/device.ts
tests/integration/stirshaken.ts
tests/lib/token.js
tests/unit/connection.ts

This adds a CallerId field onto Connection based on [this API spec](https://docs.google.com/document/d/1Wx6n4zQ-_IpEl1VtQCuiyIusqVIG4EU3tpHw-9rL1Mk/edit).
Also see the corresponding [VSP update PR](https://code.hq.twilio.com/client/voice-signaling-protocol/pull/6).

CLIENT-7583 STIR/SHAKEN

---

CHANGELOG.md
lib/twilio/preflight/preflight.ts
tests/peerconnection.js
tests/unit/preflight.ts

- [CLIENT-7786](https://issues.corp.twilio.com/browse/CLIENT-7786)
This PR fixes an issue where master audio is not muted after changing device. This PR is now making sure all output audio are muted whenever clientjs updates the output.

CLIENT-7786 | [Preflight] Fix output not muting for non default device

---

lib/twilio/device.ts

We have observed the following error happening with
`Chrome Mobile WebView`:
```
networkInformation.addEventListener is not a function
```
This commit checks if `networkInformation.addEventListener` and
`networkInformation.removeEventListener` are functions before using
them.
- [CLIENT-0000](https://issues.corp.twilio.com/browse/CLIENT-0000)

[PR202]Ensure add/removeEventListener methods are present for connection

---

CHANGELOG.md
lib/twilio/rtc/peerconnection.js
tests/peerconnection.js

- [CLIENT-7995](https://issues.corp.twilio.com/browse/CLIENT-7995)
During the ICE Gathering phase, the following steps should happen in order per WebRTC spec.
1. ICE Gathering starts
2. ICE Gathering State changes to "gathering"
3. A local ICE Candidate is gathered, and On ICE Candidate event is triggered
4. ICE Gathering State changes to "complete"
All major browsers support the above sequence. Until recently, Safari 13.1.2 has changed in behavior. The following sequence describes the new behavior.
1. ICE Gathering starts
2. A local ICE Candidate is gathered, and On ICE Candidate event is …

CLIENT-7995 | Handling out of sequence ICE Gathering events

---

CHANGELOG.md
lib/twilio/connection.ts
tests/unit/connection.ts

- [CLIENT-7909](https://issues.corp.twilio.com/browse/CLIENT-7909)
Unbinds the transportClose event when we destroy the Connection.

CLIENT-7909 | Clean up transportClose event

---

CHANGELOG.md
lib/twilio/preflight/preflight.ts
tests/unit/preflight.ts

- [CLIENT-7480](https://issues.corp.twilio.com/browse/CLIENT-7480)
When network handover happens on FF and Safari, websocket drops right away which causes a bunch of errors thrown due to retries and queued messages which is normal. As a side effect on preflight, our error handler is called multiple times and onFailed is raised multiple times. This PR updates that so we only listen to error once.

CLIENT-7480 | Preflight network handover results with error messages

---

CHANGELOG.md
lib/twilio/device.ts
lib/twilio/rtc/rtcpc.js
tests/unit/device.ts

- [CLIENT-8023](https://issues.corp.twilio.com/browse/CLIENT-8023)
Replaces Edge Legacy warning with a thrown error.

CLIENT-8023 | Deprecate Edge Legacy

---

CHANGELOG.md
lib/twilio/device.ts
tests/index.ts
tests/unit/device.ts

This is intended to address. https://github.com/twilio/twilio-client.js/issues/164
- [CLIENT-7633](https://issues.corp.twilio.com/browse/CLIENT-7633)
This PR updated our navigation behavior to call destroy (rather than just disconnectAll) and does the same for both the `unload` and `pagehide` events.

CLIENT-7633 | Call destroy on unload and pagehide

---

CHANGELOG.md
lib/twilio/connection.ts
tests/unit/connection.ts

- [CLIENT-7980](https://issues.corp.twilio.com/browse/CLIENT-7980)
Fixed an issue where the disconnect sound plays after the caller cancelled the incoming call.

CLIENT-7980 | Disconnect sound plays after connection.ignore

---

.release.json

This PR makes sure we don't output GH tokens when the git command fails. The script does:
- hides all git push output
- if push is successful, it prints "Push to origin successful"
- if push failed, it prints "Push to origin failed" and exits non-zero code
The issue we're solving however, is not happening anymore because latest version of release-tool doesn't output the errors anymore. This PR is another layer to hide the output in case release-tool is updated to show verbose logging.

Test Travis Fix

---

CHANGELOG.md
lib/twilio/connection.ts
lib/twilio/pstream.js
lib/twilio/rtc/peerconnection.js
tests/peerconnection.js
tests/pstream.js

- [CLIENT-8168](https://issues.corp.twilio.com/browse/CLIENT-8168)
Adding preflight boolean to signaling invite

CLIENT-8168 | Adding preflight boolean to signaling invite

---

CHANGELOG.md
lib/twilio/connection.ts
lib/twilio/statsMonitor.ts
tests/unit/connection.ts
tests/unit/statsMonitor.ts

- [CLIENT-7589](https://issues.corp.twilio.com/browse/CLIENT-7589)
Re-adds the original `max` threshold warning back to `packetsLostFraction` within `statsMonitor`. Now, both `max` and `maxAverage` thresholds are used.

[CLIENT-7589] Add `max` threshold warning back to `packetsLostFraction`.

---

CHANGELOG.md
lib/twilio/device.ts
lib/twilio/preflight/preflight.ts
tests/integration/preflight.ts

Changelog for 1.13.0. I also added documentation to wagtail. See drafts below. They will be live once we get green light from QE.
PreflightTest class: https://www.twilio.com/docs/admin/pages/22197/view_draft/
Device.testPreflight: https://www.twilio.com/docs/admin/pages/1773/view_draft/#testpreflight
Connection.on('warning'): https://www.twilio.com/docs/admin/pages/1772/view_draft/#onwarning-handlerwarningname-warningdata
Edit: Also renamed testPreflight to runPreflight base on discussions.

1.13.0 changelog and rename testPreflight to runPreflight

---

CHANGELOG.md
lib/twilio/connection.ts
lib/twilio/device.ts
tests/unit/connection.ts
tests/unit/device.ts

- [CLIENT-7730](https://issues.corp.twilio.com/browse/CLIENT-7730)
Introduces a new parameter for `Device.connect` and `Connection.accept` to allow for `Connection` specific ICE Servers.

[CLIENT-7730] Allow Connection specific ICE Servers

---

CHANGELOG.md
lib/browser.js
lib/twilio.ts
lib/twilio/device.ts
lib/twilio/log.ts
tests/integration/logger.ts
tests/unit/device.ts

- [CLIENT-8269](https://issues.corp.twilio.com/browse/CLIENT-8269)
This PR removes the `Device` logging options `debug` and `warning` in favor of a standardized `logLevel` description or number such as `'ERROR'` or the numerical equivalent `4`. This PR is an API change towards `twilio-client.js@2.x`.

[CLIENT-8269] Expose `loglevel` usage.

---

CHANGELOG.md
lib/twilio/device.ts
lib/twilio/preflight/preflight.ts
tests/integration/device.ts
tests/integration/edgefallback.ts
tests/integration/icenomination.ts
tests/integration/mutableOptions.ts
tests/integration/opus.ts
tests/integration/preflight.ts
tests/integration/reconnection.ts
tests/integration/stirshaken.ts
tests/unit/device.ts
tests/unit/preflight.ts

- [CLIENT-8337](https://issues.corp.twilio.com/browse/CLIENT-8337)
- [CLIENT-8338](https://issues.corp.twilio.com/browse/CLIENT-8338)
This PR includes work for both CLIENT-8337 and CLIENT-8338. This PR implements lazy signaling where a signaling connection is only made when necessary, i.e. when registering and making a call. It also changes the `Device` states.

[CLIENT-8337] and [CLIENT-8338] Lazy Signaling and Device States

---

CHANGELOG.md
lib/twilio/call.ts
lib/twilio/device.ts
lib/twilio/errors/generated.ts
lib/twilio/errors/index.ts
lib/twilio/preflight/preflight.ts
package.json
templates/constants.js
tests/integration/preflight.ts
tests/unit/call.ts
tests/unit/preflight.ts

We had some gaps where we were emitting the old Error format. This brings those up to date. See attached CHANGELOG.md changes for each error code that changed as a result.

Fix Call and Preflight to only emit TwilioError

---

lib/twilio/rtc/peerconnection.js

https://issues.corp.twilio.com/browse/VBLOCKS-1389
- Connection states are not available on VDI. Using a different mechanism to read them. This fixes insights errors since we are not sending undefined anymore when on VDI
TODO:
Fix call invite errors
Tests (different PR)

Using target PC state if connectionState is not available
